  server:
    port: 8080
  spring:
    application:
      name: twitter-like
    r2dbc:
      url: r2dbc:postgresql://localhost:5432/twitter_db
      username: postgres
      password: password
    flyway:
      url: jdbc:postgresql://localhost:5432/twitter_db
      user: postgres
      password: password
      baselineOnMigrate: true

  application:
    config:
      user-management-url: http://localhost:8081/api/v1/user







